### ISSUE TITLE
Player Sprite is not Reset after Death

### ISSUE THREAD

**Issue by Pathemeous** [Pathemeous/sem-group-4#144]
When a Player dies, his image remains as-is before his death. This means that he will keep looking left or right when the level restarts. (until further input, which then overrides the wrong sprite properly).

Credits to Bram for finding this bug.

< bug

**Comment by BCrlrd** [comment]
Well, I'm fine with having this bug. It's also in the original game if I'm not mistaking.

< bug

**Comment by Pathemeous** [comment]
I meant that you found it, not that you created it. (which you didn't, it either has always been there or @cathmer4 introduced it when he added Player spawns.

**Comment by BCrlrd** [comment]
I know that's what you meant, I'm just saying I don't see the point in fixing it.

**Comment by cathmer4** [comment]
It was indeed introduced with the Player spawns. It would be really easy to fix. However, I agree with Bram that it's not really worth fixing, because it would also look weird if the player looks forward all of a sudden when he dies.
