### ISSUE TITLE
current keybindings (options) JSON is too complex

### ISSUE THREAD

**Issue by Pathemeous** [Pathemeous/sem-group-4#152]
The current JSON that contains the contols settings is overly complex. Its structure even requires a dedicated object (<code>KeyBindEntry</code>) to be able to store the JSON contents.

Refactoring this would greatly benefit the maintainability and extendability of the <code>KeyBindHelper</code> (responsible for parsing the JSON), and allow it to be self-contained, in the sense that it will be able to deliver finalised objects to other classes, such as <code>Settings.class</code>

We should consider refactoring this in a future milestone.

The Pull Request adding this part of the system is #150 

< organisation, performance

**Comment by BCrlrd** [comment]
This is the case because I had only worked with json once before, and it had a layout similar to this. It was the only one I knew how to make.

< organisation

**Comment by Pathemeous** [comment]
That is understandable. The issue is here not to blame anyone, merely to
remind us to fix this at some point in the near future.

< review

**Comment by cathmer4** [comment]
Pull request has been opened to fix this.

**Comment by Pathemeous** [comment]
Solved with #153
