### ISSUE TITLE
Build fails when Fonts are created and loaded via the ResoucesWrapper

### ISSUE THREAD

**Issue by Pathemeous** [Pathemeous/sem-group-4#182]
See #175 and #181.

fonts loaded by other means (such as those loaded in the HighScoreState) do not cause build failures.

only the build fails, resulting in the following error:
```
[ERROR] /home/travis/build/Pathemeous/sem-group-4/src/main/java/nl/tudelft/semgroup4/
resources/ResourcesWrapper.java:[373,36] cannot find symbol
  symbol:   class Font
  location: class nl.tudelft.semgroup4.resources.ResourcesWrapper
```

**Comment by BCrlrd** [comment]
I have used a workaround for this in LoggerSetScreen by adding the method createFont to the resourcewrapper. All this method does is use the normal createFont, but we will be able to mock it as it's one of our own methods. You can look at lines 42 and 43 in LoggerSetScreen to see how I used it.

**Comment by Pathemeous** [comment]
Has been fixed.
