### ISSUE TITLE
Bubbles bounce out of bounds

### ISSUE THREAD

**Issue by cathmer4** [Pathemeous/sem-group-4#193]
Because the collisionhandling between Bubbles and Walls is not 100% waterproof, the bubbles sometimes bounce out of the level (only happens in levels with moving walls). When the player has then cleared all the bubbles he sees, the level is not completed because there is still one Bubble in the list, that is not visible and will never come back in the Level. 

To fix this, either a Bubble has to be destroyed when it is out of bounds, or the collision between Walls and Bubbles needs to be updated so that Bubbles cannot bounce out of the Level. The second solution is preferred, but is also hardest to implement.

**Comment by BCrlrd** [comment]
This bug has been fixed in a previous release.
As the person didn't link to this issue I can't find the actual pull request.

< bug
