### ISSUE TITLE
Can't shoot

### ISSUE THREAD

**Issue by BCrlrd** [Pathemeous/sem-group-4#202]
Sometimes when a projectile disappears after hitting a moving wall the player is unable to shoot.

**Comment by BCrlrd** [comment]
After filing this report I have attempted to reproduce it and have been unable to.

**Comment by Pathemeous** [comment]
I'm sorry to hear. Adoption is always a very humane alternative.

**Comment by BCrlrd** [comment]
I have to admit I'm rather happy I don't shoot projectiles from my genitals.

**Comment by Pathemeous** [comment]
To each their own we'll say.

**Comment by BCrlrd** [comment]
As this bug hasn't occurred again I'm closing the issue.
